export const tokens = {
  deepSlate:    '#0E1117',
  slateMid:     '#1A2030',
  slateLight:   '#2C3547',
  starkWhite:   '#F5F6FA',
  whiteDim:     '#B8BED0',
  electric:     '#00E5A0',
  electricDim:  'rgba(0,229,160,0.12)',
  electricGlow: 'rgba(0,229,160,0.4)',
  fontMain:     "'DM Sans', sans-serif",
  fontMono:     "'Space Mono', monospace",
};

export const s = {
  label: {
    fontFamily: tokens.fontMono,
    fontSize: '11px',
    letterSpacing: '3px',
    textTransform: 'uppercase',
    color: tokens.electric,
    marginBottom: '16px',
    display: 'block',
  },
  sectionTitle: {
    fontFamily: tokens.fontMain,
    fontSize: 'clamp(30px, 4vw, 54px)',
    fontWeight: 700,
    letterSpacing: '-2px',
    lineHeight: 1.08,
    color: tokens.starkWhite,
    marginBottom: '16px',
  },
  body: {
    fontFamily: tokens.fontMain,
    fontSize: '16px',
    fontWeight: 300,
    lineHeight: 1.85,
    color: tokens.whiteDim,
  },
  card: {
    background: tokens.slateMid,
    border: `1px solid ${tokens.slateLight}`,
    borderRadius: '12px',
    padding: '32px',
    transition: 'border-color 0.3s, background 0.3s',
  },
  btnPrimary: {
    padding: '14px 28px',
    background: tokens.electric,
    color: tokens.deepSlate,
    fontFamily: tokens.fontMain,
    fontWeight: 600,
    fontSize: '15px',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s',
    letterSpacing: '-0.3px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
  },
  btnGhost: {
    padding: '14px 28px',
    background: 'transparent',
    color: tokens.starkWhite,
    fontFamily: tokens.fontMain,
    fontWeight: 500,
    fontSize: '15px',
    border: `1px solid ${tokens.slateLight}`,
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
  },
  section: { padding: '100px 40px', maxWidth: '1200px', margin: '0 auto' },
  divider: { border: 'none', borderTop: `1px solid ${tokens.slateLight}`, margin: 0 },
};
